services:
  php:
    image: yiisoftware/yii2-php:8.3-fpm-nginx
    volumes:
      - ./src:/app

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-verysecret}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-yii2}
      - MYSQL_USER=${MYSQL_USER:-yii2}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-secret}

  backend:
    build: src/backend
    ports:
      - 21080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./src:/app
    depends_on:
      - mysql

  frontend:
    build: src/frontend
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./src:/app
    depends_on:
      - mysql
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8888:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - mysql